import { createMenuItem, defaultMenuItems, MenuItem } from '../../shared/menu';

//FIXME: Verwoben mit den Modellen, Routes, Guards und Translations (Name und Icon)
export const menuItems: MenuItem[] = [
  {
    title: 'Dashboard',
    icon: 'dashboard',
    route: '/dashboard',
    needsLogin: true,
    needsAdmin: false,
    screens: true,
  },
  {
    title: 'Tiere',
    icon: 'pets',
    route: '/animals',
    needsLogin: true,
    needsAdmin: false,
    screens: true,
  },
  {
    title: 'Tierheime',
    icon: 'home',
    route: '/shelters',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  {
    title: 'Gehege',
    icon: 'domain',
    route: '/enclosures',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  {
    title: 'Interessenten',
    icon: 'groups',
    route: '/adopters',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  {
    title: 'Anträge',
    icon: 'assignment',
    route: '/adoptionApplications',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  {
    title: 'Verträge',
    icon: 'favorite',
    route: '/adoptionContracts',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  {
    title: 'Gesundheitsreports',
    icon: 'local_hospital',
    route: '/animalHealths',
    needsLogin: true,
    needsAdmin: true,
    screens: true,
  },
  ...defaultMenuItems,
];
